import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import NavbarLeft from './_components/navbar-left';
import { Toaster } from '@/components/ui/sonner';

const interFont = Inter({
  subsets: ['latin'],
  weight: ['700'],
  style: ['normal'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Dashboard - Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${interFont.variable} h-[992px] min-h-[800px] w-[1280px] overflow-y-auto bg-white antialiased`}
      >
        <div className="flex">
          <NavbarLeft />
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
