import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import NavbarLeft from "./_components/navbar-left";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["700"],
  style: ["normal"],
  variable: "--font-inter",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dashboard - Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${interFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <NavbarLeft />
          {children}
        </div>
      </body>
    </html>
  );
}
